# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b8e65e183a39346e9999e70d34959318f34b8964bf3a378afa0328f1d83d5e4403b526bbc24c6c7b131864c39f179191ac5160e6eb3963d758481eba36c4153

test:
  secret_key_base: 92bc996edccb001739ffb18b8915831e9e7f41cbfc5978ba65739ddbc26d6dfd5dd9210064037dfeee2cd7743191fe33fac55bac6ce64394d7f5fb894fc19523

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
